server:
  port: ${SERVER_PORT:8083}

spring:
  profiles:
    default: dev
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    root: INFO
    com.bookstore: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
